---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
  - app-sealed-secret.yaml

namespace: "calibre"
namePrefix: "calibre-"
images:
  - name: "crocodilestick/calibre-web-automated"
    newTag: "V3.1.4"

configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
  - name: app-secret-sentinel
    files:
      - app-sealed-secret.yaml
