---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          image: "crocodilestick/calibre-web-automated:V3.1.4"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "app-config"
            - secretRef:
                # managed manually because this is from a sealed secret
                name: "app-secret"
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /config
            - name: calibre-library
              mountPath: /calibre-library
            - name: calibre-import
              mountPath: /cwa-book-ingest
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: calibre-library
          hostPath:
            path: /mnt/calibre
            type: Directory
        - name: calibre-import
          hostPath:
            path: /media/calibre-import
            type: Directory
